development:
  adapter: sqlite3
  database: db/sounds_goood.sqlite3

production:
  encoding: unicode
  adapter: postgresql
  username: jaaqihpgbpeclq
  port: 5432
  host: ec2-54-235-104-186.compute-1.amazonaws.com
  database: desbpsi0i1u3ns
  password: KaRlWxepeNPs7p_O1tUpGOSeqg
